---
version: "3"

tasks:
  default:
    cmds:
      - task: help

  init:
    desc: Init project
    silent: true
    cmds:
      - poetry install

  clean:
    desc: Cleanup project
    silent: true
    cmds:
      - poetry env remove --all
      - rm -rf .pytest_cache
      - rm -rf .ruff_cache
      - rm -rf output
      - rm -rf tests/__pycache__

  reinit:
    desc: Reinit project
    silent: true
    cmds:
      - task: clean
      - task: init

  lint:
    desc: Run project linters
    silent: true
    cmds:
      - poetry run cz check --rev-range 33eab2d..HEAD
      - poetry run ruff check --config .config/ruff.toml
      - poetry run ruff format --config .config/ruff.toml --check --diff
      - poetry run yamllint -c .config/yamllint.yml . --strict

  test:
    desc: Run project tests
    silent: true
    cmds:
      - rm -rf output
      - poetry run pytest tests -v
      - |
        cd output
        task init
        task clean
        task reinit
        task lint
        task test

  pipeline:
    desc: Run lint and test tasks
    silent: true
    cmds:
      - task: lint
      - task: test

  help:
    desc: Display help
    silent: true
    cmds:
      - task --list
