---
version: "3"

tasks:
  default:
    cmds:
      - task: help

  init:
    desc: Init project
    silent: true
    cmds:
      - poetry install

  clean:
    desc: Cleanup project
    silent: true
    cmds:
      - poetry env remove --all

  reinit:
    desc: Reinit project
    silent: true
    cmds:
      - task: clean
      - task: init

  test:
    desc: Run project tests
    silent: true
    cmds:
      - rm -rf output
      - poetry run copier copy --vcs-ref HEAD --data project_name="test" . output
      - poetry run pytest -v

  help:
    desc: Display help
    silent: true
    cmds:
      - task --list
