---
version: "3"

tasks:
  default:
    cmds:
      - task: help

  init:
    desc: Init project
    silent: true
    cmds:
      - poetry install

  clean:
    desc: Cleanup project
    silent: true
    cmds:
      - poetry env remove --all
      - rm -rf .pytest_cache
      - rm -rf output
      - rm -rf tests/__pycache__

  reinit:
    desc: Reinit project
    silent: true
    cmds:
      - task: clean
      - task: init

  lint:
    desc: Run project linters
    silent: true
    cmds:
      - poetry run ruff check --config .config/ruff.toml
      - poetry run ruff format --config .config/ruff.toml --check --diff
      - poetry run yamllint -c .config/yamllint.yml . --strict

  test:
    desc: Run project tests
    silent: true
    cmds:
      - poetry run pytest -v

  help:
    desc: Display help
    silent: true
    cmds:
      - task --list
