---
name: lint

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

jobs:
  lint:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: ["cz-check", "ruff", "yamllint", "hadolint"]
    env:
      TASK_VERSION: 3.41.0
      HADOLINT_VERSION: 2.12.0
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          wget https://github.com/go-task/task/releases/download/v$TASK_VERSION/task_linux_amd64.deb
          sudo dpkg -i task_linux_amd64.deb
          wget -q -P /tmp https://github.com/hadolint/hadolint/releases/download/v$HADOLINT_VERSION/hadolint-Linux-x86_64
          mv /tmp/hadolint-Linux-x86_64 /usr/local/bin/hadolint
          chmod +x /usr/local/bin/hadolint
          pip install poetry
          task init
      - name: Run linter ${{ matrix.linter }}
        run: task lint:${{ matrix.linter }}
